package com.synex.domain;

public enum Stage {
  START,
  ASK_CITY,
  ASK_DATES,
  ASK_GUESTS,
  ASK_FILTERS,
  SHOW_HOTELS,
  ASK_SERVICES,
  ASK_ROOM_TYPE,
  ASK_NUM_ROOMS,
  ASK_CUSTOMER_NAME,
  SHOW_SUBTOTAL,
  ASK_ANOTHER,
  ASK_PAYMENT,
  ASK_FEEDBACK,
  DONE, ASK_FILTER_REFINE
}
